version: '3'
services: 
    react-app:
        build: 
            context: .
            dockerfile: Dockerfile.dev
        ports: 
            - "3000:3000"
        stdin_open: true
        volumes: 
            - /app/node_modules
            - .:/app
    server:
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - "8000:8000"
        volumes: 
            - /app/node_modules
            - .:/app
        command: ["npm", "run", "start:server"]