version: '3'
services: 
    react-app:
        build: 
            context: ./client
            dockerfile: Dockerfile.dev
        ports: 
            - "3000:3000"
        stdin_open: true
        volumes: 
            - /app/node_modules
            - ./client:/app
    server:
        build:
            context: ./server
            dockerfile: Dockerfile.dev
        ports:
            - "8000:8000"
        volumes: 
            - /app/node_modules
            - ./server:/app